### PR TITLE
Change Send RPID/PAI config for Mywic

### PR DESCRIPTION
**Pull request by andrea-marchionni**
Change Mywic configuration (Send RPID/PAI to both) to set Outbound CallerID

### CODE REVIEW

**Comment by andrea-marchionni** [comment]
https://github.com/nethesis/dev/issues/6176

**Comment by gsanchietti** [comment]
The product is in software freeze: it's not a good idea change an existing default.
Can we please avoid it?

Is the change still possible from FreePBX UI?

**Review by gsanchietti — CHANGES_REQUESTED** [review]
Please let's see if we can use a different strategy

**Comment by Stell0** [comment]
Changing default for new trunks is enough since old configuration only cause minor issues

**Pull request merged**
